[MySQLConfig]
user = handy
password = handy
host = ec2-13-51-79-239.eu-north-1.compute.amazonaws.com
database = framework

[SimulationConfig]
simulator_hardware = ibmq_qasm_simulator
; simulator_hardware = simulator_mps

[MathConfig]
bit_format = {0:0127b}

[GeneralConfig]
activate_debugging_time = 1

[TypeConfig]
; program_type = Polar
program_type = PolarSimulation
; program_type = PolarRepeat
; program_type = Calibration
; program_type = CalibrationSherbrooke
; program_type = CalibrationSherbrookeQEM
; program_type = CalibrationScale
; program_type = Testing

; PolarSimuilation
[QuantumConfigPolarSimulation]
hardware_name = ibm_brisbane
; hardware_name = ibm_sherbrooke
; base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n2/
; base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n3/
base_folder = ~/qem_platform/circuits/polarcode/x/state_prep/n4/
; base_folder = ~/qem_platform/circuits/polarcode/z/measure_all/n2/
; base_folder = ~/qem_platform/circuits/polarcode/z/measure_all/n3/
initialized_triq = 1
token_number = 1
; triq_measurement_type = polar_meas  
; triq_measurement_type = polar_mix
triq_measurement_type = polar
shots = 10
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
rep_delay = 0.0005
runs = 1
repetition = 1
run_in_simulator = 0
user_id = 99
remaining = 1
skip_update_simulator = 1
noisy_simulator = 1
noise_level = 0.1,0.2,0.4,0.6,0.8,1.0
; noise_level = 0.2, 0.4
send_to_backend = 1



; Polar
[QuantumConfigPolar]
; hardware_name = ibm_brisbane
hardware_name = ibm_sherbrooke
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
; base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n2/
; base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n3/
; base_folder = ~/qem_platform/circuits/polarcode/z/measure_all/n3/
; base_folder = ~/qem_platform/circuits/polarcode/x/state_prep/n2/
; base_folder = ~/qem_platform/circuits/polarcode/x/state_prep/n3/
base_folder = ~/qem_platform/circuits/polarcode/x/state_prep/n4/
; base_folder = ~/qem_platform/circuits/polarcode/z/state_prep/n4/
; shots = 20000
shots = 7500
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 1
run_in_simulator = 0
user_id = 14
triq_measurement_type = polar
remaining = 300
token_number = 5
skip_update_simulator = 1
noisy_simulator = 0
noise_level = 1.0
send_to_backend = 1



; PolarRepeat
[QuantumConfigPolarRepeat]
hardware_name = ibm_brisbane
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n6/
shots = 10
rep_delay = 0.0005
runs = 1
repetition = 3
initialized_triq = 0
run_in_simulator = 0
user_id = 10
triq_measurement_type = polar
remaining = 3
token_number = 20
skip_update_simulator = 1
noisy_simulator = 1
noise_level = 0.1,0.2,0.4,0.6,0.8,1.0,1.5,2.0,2.5 
send_to_backend = 1

; Calibration
[QuantumConfigCalibration]
hardware_name = ibm_brisbane
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_triq/
shots = 10000
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 1
run_in_simulator = 0
user_id = 15
triq_measurement_type = normal
remaining = 200
token_number = 1
skip_update_simulator = 0
noisy_simulator = 0
noise_level = 1.0
send_to_backend = 1

; CalibrationSherbrooke
[QuantumConfigCalibrationSherbrooke]
hardware_name = ibm_sherbrooke
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_triq/
shots = 10000
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 1
run_in_simulator = 0
user_id = 16
triq_measurement_type = normal
remaining = 200
token_number = 1
skip_update_simulator = 0
noisy_simulator = 0
noise_level = 1.0
send_to_backend = 1

; CalibrationSherbrookeQEM
[QuantumConfigCalibrationSherbrookeQEM]
hardware_name = ibm_sherbrooke
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_triq/
shots = 10000
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 1
run_in_simulator = 0
user_id = 17
triq_measurement_type = normal
remaining = 300
token_number = 1
skip_update_simulator = 0
noisy_simulator = 0
noise_level = 1.0
send_to_backend = 0

; Calibration Scale
[QuantumConfigCalibrationScale]
hardware_name = ibm_brisbane
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/Quantum_benchmarks/Medina/BV/
; base_folder = ~/Quantum_benchmarks/Medina/QFT/
shots = 10000
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 1
run_in_simulator = 0
user_id = 13
triq_measurement_type = normal
remaining = 150
token_number = 1
skip_update_simulator = 0
send_to_backend = 1

; Testing
[QuantumConfigTesting]
hardware_name = ibm_sherbrooke
ibm_cloud_instance = Qiskit Runtime-ucm
optimization_level = 0
resilience_level = 0
base_folder = ~/qem_platform/circuits/testing/
shots = 20000
rep_delay = 0.0005
runs = 1
repetition = 1
initialized_triq = 0
run_in_simulator = 0
user_id = 99
triq_measurement_type = normal
remaining = 10
token_number = 1
skip_update_simulator = 0
noisy_simulator = 1
noise_level = 0.0,0.1,0.5,1.0,1.5,2.0,2.5 
send_to_backend = 1

# # handy UCM API cloud
# token = isz-S9_mFwh8ikGssvCSoxoL3yk6mCyAkmsKoRyI8O0P
; ------------------------------------
; base_folder = ~/Quantum_benchmarks/Medina/adder/
; base_folder = ~/Quantum_benchmarks/Medina/BV/
; base_folder = ~/Quantum_benchmarks/Medina/QFT/
; base_folder = ~/Quantum_benchmarks/Medina/AND/
; base_folder = ~/Quantum_benchmarks/Medina/grover/
; base_folder = ~/Quantum_benchmarks/Medina/OR/
; base_folder = ~/Quantum_benchmarks/Medina/MQT

; [QuantumConfig]
; hardware_name = ibm_brisbane
; ; hardware_name = ibm_brisbane_32
; ; hardware_name = ibm_osaka
; ; hardware_name = ibm_kyoto
; ; hardware_name = ibm_perth
; # hardware_name = ibm_algiers
; # hardware_name = simulator_mps
; ibm_cloud_instance = Qiskit Runtime-ucm
; optimization_level = 0
; resilience_level = 0
; shots = 10000
; rep_delay = 0.0005
; runs = 1
; repetition = 1
; initialized_triq = 1
; run_in_simulator = 0
; user_id = 11
; triq_measurement_type = normal

; ; base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_run/
; ; base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_executed/
; base_folder = ~/Quantum_benchmarks/Paper_circuits/n_7_triq/
; ; base_folder = ~/qem_platform/circuits/polarcode/z/state_prep/n4/
; ; base_folder = ~/qem_platform/circuits/polarcode/x/state_prep/n4/
; ; base_folder = ~/qem_platform/circuits/polarcode/z/measure_all/n2/
; ; base_folder = ~/qem_platform/circuits/polarcode/x/measure_all/n2/